version: "3"

includes:
  utils: "tools/yscope-dev-utils/exports/taskfiles/utils/utils.yaml"
  lint: "taskfiles/lint.yaml"

vars:
  G_BUILD_DIR: "{{.ROOT_DIR}}/build"

tasks:
  clean: "rm -rf '{{.G_BUILD_DIR}}'"

  init:
    internal: true
    silent: true
    run: "once"
    cmd: "mkdir -p '{{.G_BUILD_DIR}}'"
