version: "3"

set: ["u", "pipefail"]
shopt: ["globstar"]

includes:
  deps: "taskfiles/deps.yaml"
  docs: "taskfiles/docs.yaml"
  examples: "taskfiles/examples.yaml"
  lint: "taskfiles/lint.yaml"
  log-surgeon: "taskfiles/log-surgeon.yaml"
  test: "taskfiles/test.yaml"

vars:
  # General variables
  # This must match the package name in CMakeLists.txt.
  G_CMAKE_PACKAGE_NAME: "log_surgeon"

  # Build directories
  G_BUILD_DIR: "{{.ROOT_DIR}}/build"
  G_EXAMPLES_BUILD_DIR: "{{.G_BUILD_DIR}}/examples"
  G_EXAMPLES_DEBUG_BUILD_DIR: "{{.G_EXAMPLES_BUILD_DIR}}/debug"
  G_EXAMPLES_RELEASE_BUILD_DIR: "{{.G_EXAMPLES_BUILD_DIR}}/release"
  G_LOG_SURGEON_BUILD_DIR: "{{.G_BUILD_DIR}}/{{.G_CMAKE_PACKAGE_NAME}}"
  G_LOG_SURGEON_DEBUG_BUILD_DIR: "{{.G_LOG_SURGEON_BUILD_DIR}}/debug"
  G_LOG_SURGEON_RELEASE_BUILD_DIR: "{{.G_LOG_SURGEON_BUILD_DIR}}/release"

tasks:
  clean: "rm -rf '{{.G_BUILD_DIR}}'"

  init:
    internal: true
    silent: true
    run: "once"
    cmd: "mkdir -p '{{.G_BUILD_DIR}}'"
