version: "3"

tasks:
  debug:
    deps:
      - ":deps:all"
    cmds:
      - task: ":utils:cmake:generate"
        vars:
          BUILD_DIR: "{{.G_LOG_SURGEON_BUILD_DIR}}/debug"
          EXTRA_ARGS:
            - "-DCMAKE_BUILD_TYPE=debug"
          SOURCE_DIR: "{{.ROOT_DIR}}"
      - task: ":utils:cmake:build"
        vars:
          BUILD_DIR: "{{.G_LOG_SURGEON_BUILD_DIR}}/debug"

  release:
    deps:
      - ":deps:all"
    cmds:
      - task: ":utils:cmake:generate"
        vars:
          BUILD_DIR: "{{.G_LOG_SURGEON_BUILD_DIR}}/release"
          EXTRA_ARGS:
            - "-DCMAKE_BUILD_TYPE=release"
          SOURCE_DIR: "{{.ROOT_DIR}}"
      - task: ":utils:cmake:build"
        vars:
          BUILD_DIR: "{{.G_LOG_SURGEON_BUILD_DIR}}/release"

  clean-debug:
    deps:
      - task: ":utils:cmake:clean"
        vars:
          BUILD_DIR: "{{.G_LOG_SURGEON_BUILD_DIR}}/debug"

  clean-release:
    deps:
      - task: ":utils:cmake:clean"
        vars:
          BUILD_DIR: "{{.G_LOG_SURGEON_BUILD_DIR}}/release"

  examples-debug:
    vars:
      INSTALL_PREFIX: "{{.G_EXAMPLES_BUILD_DIR}}/deps/log_surgeon/debug"
    deps:
      - "debug"
    cmds:
      - task: ":install:debug"
        vars:
          PREFIX: "{{.INSTALL_PREFIX}}"
      - task: ":utils:cmake:generate"
        vars:
          BUILD_DIR: "{{.G_EXAMPLES_BUILD_DIR}}/debug"
          EXTRA_ARGS:
            - "-DCMAKE_BUILD_TYPE=debug"
            - "-Dlog_surgeon_ROOT={{.INSTALL_PREFIX}}"
          SOURCE_DIR: "{{.ROOT_DIR}}/examples"
      - task: ":utils:cmake:build"
        vars:
          BUILD_DIR: "{{.G_EXAMPLES_BUILD_DIR}}/debug"

  examples-release:
    vars:
      INSTALL_PREFIX: "{{.G_EXAMPLES_BUILD_DIR}}/deps/log_surgeon/release"
    deps:
      - "release"
    cmds:
      - task: ":install:release"
        vars:
          PREFIX: "{{.INSTALL_PREFIX}}"
      - task: ":utils:cmake:generate"
        vars:
          BUILD_DIR: "{{.G_EXAMPLES_BUILD_DIR}}/release"
          EXTRA_ARGS:
            - "-DCMAKE_BUILD_TYPE=release"
            - "-Dlog_surgeon_ROOT={{.INSTALL_PREFIX}}"
          SOURCE_DIR: "{{.ROOT_DIR}}/examples"
      - task: ":utils:cmake:build"
        vars:
          BUILD_DIR: "{{.G_EXAMPLES_BUILD_DIR}}/release"

  examples-clean-debug:
    deps:
      - task: ":utils:cmake:clean"
        vars:
          BUILD_DIR: "{{.G_EXAMPLES_BUILD_DIR}}/debug"

  examples-clean-release:
    deps:
      - task: ":utils:cmake:clean"
        vars:
          BUILD_DIR: "{{.G_EXAMPLES_BUILD_DIR}}/release"
