# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "LogEvent",
    "LogType",
    "Parser",
    "Variable",
]

@typing.final
class LogEvent:
    r"""
    A parsed log event.
    """
    @property
    def log_type(self) -> LogType: ...
    @property
    def variables(self) -> list[Variable]: ...
    @property
    def message(self) -> str: ...
    def __str__(self) -> str: ...

@typing.final
class LogType:
    r"""
    A log type template showing the structure of a log event.
    """
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __str__(self) -> builtins.str: ...

@typing.final
class Parser:
    r"""
    High-performance log parser using DFA-based pattern matching.
    """
    def __new__(cls, debug: builtins.bool = False) -> Parser: ...
    def add_variable_pattern(self, name: builtins.str, pattern: builtins.str, *, priority: builtins.int = 0) -> None:
        r"""
        Add a named pattern with ``(?<capture_name>...)`` groups.
        
        Higher priority patterns are matched first. Default is 0.
        """
    def set_delimiters(self, delimiters: builtins.str) -> None:
        r"""
        Set token boundary characters. Raises if empty.
        """
    def compile(self) -> None:
        r"""
        Compile patterns into the matching engine. Must be called before parsing.
        """
    def set_input_stream(self, input: str | bytes | typing.IO[bytes]) -> None:
        r"""
        Set the input to parse (string, bytes, or readable file object).
        """
    def next_log_event(self) -> typing.Optional[LogEvent]:
        r"""
        Get the next parsed event, or ``None`` at end of input.
        """
    def done(self) -> builtins.bool:
        r"""
        Check if all input has been consumed.
        """

@typing.final
class Variable:
    r"""
    A matched variable within a log event.
    """
    @property
    def name(self) -> str: ...
    @property
    def text(self) -> str: ...
    @property
    def captures(self) -> dict[str, list[str]]: ...
    def __repr__(self) -> builtins.str: ...

