name: "build"

on:
  pull_request:
    paths: &monitored_paths
      - ".github/workflows/build.yaml"
      - "CMakeLists.txt"
      - "examples/**/*"
      - "src/**/*"
      - "taskfile.yaml"
      - "taskfiles/**/*"
      - "tools/yscope-dev-utils"
      - "tests/**/*"
  push:
    paths: *monitored_paths
  workflow_call:

concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  # Cancel in-progress jobs for efficiency
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os:
          - "macos-15"
          - "ubuntu-22.04"
          - "ubuntu-24.04"
        build_type:
          - "debug"
          - "release"
    runs-on: "${{matrix.os}}"
    steps:
      - uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd"  # v6.0.2
        with:
          submodules: "recursive"

      - uses: "./tools/yscope-dev-utils/exports/github/actions/install-go-task"

      - uses: "./tools/yscope-dev-utils/exports/github/actions/install-uv"

      - name: "Build and run unit tests"
        run: "task test:run-${{matrix.build_type}}"

      - name: "Print test log on failure"
        if: "failure()"
        run: "cat ./build/log-surgeon/Testing/Temporary/LastTest.log"

      - name: "Build and run examples"
        run: |-
          task examples:build-${{matrix.build_type}}
          ./build/examples/${{matrix.build_type}}/buffer-parser ./examples/schema.txt README.md
          ./build/examples/${{matrix.build_type}}/reader-parser ./examples/schema.txt README.md
          ./build/examples/${{matrix.build_type}}/intersect-test
