name: "lint"

on:
  pull_request:
  push:
  schedule:
    # Run daily at 00:15 UTC (the 15 is to avoid periods of high load)
    - cron: "15 0 * * *"
  workflow_dispatch:

concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  # Cancel in-progress jobs for efficiency
  cancel-in-progress: true

jobs:
  lint:
    strategy:
      matrix:
        os:
          - "macos-15"
          - "ubuntu-24.04"
    runs-on: "${{matrix.os}}"
    steps:
      - uses: "actions/checkout@v4"
        with:
          submodules: "recursive"

      - uses: "actions/setup-python@v5"
        with:
          python-version: "3.8"

      - name: "Install task"
        run: "npm install -g @go-task/cli"

      - if: "matrix.os == 'macos-15'"
        name: "Install coreutils (for md5sum)"
        run: "brew install coreutils"

      - name: "Run lint task"
        run: "task lint:check"
